version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  frontend:
    build: ./Dashboard
    ports:
      - "5173:5173"
    volumes:
      - ./Dashboard:/app
      - /app/node_modules
    restart: unless-stopped